name: Build Yocto

on:
    workflow_dispatch:

jobs:
    pull-source-build-and-release:
        runs-on: ubuntu-22.04
    
        steps:
        - name: Install Google Repo tool
          run: |
            mkdir -p ~/bin 
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo 
            chmod a+x ~/bin/repo 
            export PATH=~/bin:$PATH 

        - name: Initialize Repo
          run: |
            mkdir -p ~/sources
            cd ~/sources
            repo init -u https://github.com/lucas-vallery/raspberrypi-repo-manifest -m manifest.xml -b kirkstone
      
        - name: Sync Repo
          run: |
            cd ~/sources
            repo sync