name: Build Yocto

on:
    workflow_dispatch:

jobs:
    pull-source-build-and-release:
        runs-on: ubuntu-22.04
    
        steps:
        - name: Build directory tree
          run: |
            mkdir -p ~/layers
            mkdir -p ~/build

        - name: Install Google Repo tool
          run: |
            sudo apt-get install repo -y 

        - name: ICheckout manifest and download layers
          run: |
            cd ~/layers
            repo init -u https://github.com/lucas-vallery/raspberrypi-repo-manifest -m manifest.xml -b kirkstone
            repo sync

        - name: Source env
          run: |
            cd ~
            source ~/layers/poky/oe-init-build-env ~/build

        - name: Yocto build
          run: |
            bitbake core-image-base



        