name: Build Yocto

on:
    workflow_dispatch:

jobs:
    pull-source-build-and-release:
        runs-on: ubuntu-22.04
    
        steps:
        - name: Install Google Repo tool
          run: |
            sudo apt-get install repo -y 

        - name: Initialize Repo
          run: |
            mkdir -p ~/sources
            cd ~/sources
            repo init -u https://github.com/lucas-vallery/raspberrypi-repo-manifest -m manifest.xml -b kirkstone
      
        - name: Sync Repo
          run: |
            cd ~/sources
            repo sync