name: Build Yocto

on:
    workflow_dispatch:

jobs:
    pull-source-build-and-release:
        runs-on: ubuntu-22.04
    
        steps:
        - name: Install Google Repo tool
          run: |
            sudo apt-get install repo -y 

        - name: Initialize Repo and checkout manifest
          run: |
            mkdir -p ~/sources
            cd ~/sources
            repo init -u https://github.com/lucas-vallery/raspberrypi-repo-manifest -m manifest.xml -b kirkstone
      
        - name: Sync Repo
          run: |
            cd ~/sources
            repo sync

        - name: Checkout Yocto conf files
          uses: actions/checkout@v4
          with:
            repository: lucas-vallery/raspberrypi-zero-conf
            token: ${{ secrets.GITHUB_TOKEN }}
            path: yocto-conf

        - name: Move Yocto conf files
          run: |
            mv yocto-conf ~/yocto-conf

        - name: Checkout Yocto build script
          uses: actions/checkout@v4
          with:
            repository: lucas-vallery/raspberry-zero-yocto-build-script
            token: ${{ secrets.GITHUB_TOKEN }}
            path: build-script
            ref: kirkstone

        - name: Move Yocto build script
          run: |
            mv build-script ~/build-script

        - name: Log in to GitHub Container Registry
          run: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Pull docker file
          run: |
            docker pull ghcr.io/lucas-vallery/yocto-build-container:latest    

        - name: Check home
          run: |
            cd ~/
            ls
        - name: Check docker
          run: |
            docker list image