name: Build Yocto

on:
    workflow_dispatch:

jobs:
    pull-source-build-and-release:
        runs-on: ubuntu-22.04
    
        steps:
        - name: Build directory tree
          run: |
            mkdir -p ~/layers
            mkdir -p ~/build

        - name: Setup build environment
          run: |
            sudo apt update
            sudo apt install chrpath diffstat -y

        - name: Install Google Repo tool
          run: |
            sudo apt-get install repo -y 

        - name: Checkout manifest and download layers
          run: |
            cd ~/layers
            repo init -u https://github.com/lucas-vallery/raspberrypi-repo-manifest -m manifest.xml -b kirkstone
            repo sync

        - name: Cache downloads and sstate
          uses: actions/cache@v4
          with:
            path: |
              ~/build/downloads
              ~/build/sstate-cache
            key: ${{ runner.os }}-downloads-sstate
            restore-keys: |
              ${{ runner.os }}-downloads-sstate

        - name: Yocto build
          run: |
            cd ~
            source ~/layers/poky/oe-init-build-env ~/build
            bitbake core-image-base
            



        